import 'package:flutter/material.dart';
import 'package:walnut_home_page/data/protocol_engine_dummy_data.dart';
import 'package:walnut_home_page/models/protocol_engine.dart';
import 'package:walnut_home_page/protocol_engine/protocol_progress_screen.dart';
import 'package:walnut_home_page/protocol_engine/protocol_weekly_roadmap_screen.dart';

class ProtocolEngineDashboard extends StatelessWidget {
  const ProtocolEngineDashboard({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '90-Day Protocol',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primaryColor: const Color(0xFF11D473),
        scaffoldBackgroundColor: const Color(0xFFF6F8F7),
        fontFamily: 'Manrope',
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF11D473),
          brightness: Brightness.light,
        ),
      ),
      darkTheme: ThemeData(
        primaryColor: const Color(0xFF11D473),
        scaffoldBackgroundColor: const Color(0xFF102219),
        fontFamily: 'Manrope',
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF11D473),
          brightness: Brightness.dark,
        ),
      ),
      home: const ProtocolScreen(),
    );
  }
}

class ProtocolScreen extends StatefulWidget {
  const ProtocolScreen({Key? key}) : super(key: key);

  @override
  State<ProtocolScreen> createState() => _ProtocolScreenState();
}

class _ProtocolScreenState extends State<ProtocolScreen> {
  final ScrollController _scrollController = ScrollController();
  bool _showTitle = false;
  late final ProtocolEngine protocol;

  @override
  void initState() {
    super.initState();
    protocol = getDummyProtocol();
    _scrollController.addListener(() {
      if (_scrollController.offset > 60 && !_showTitle) {
        setState(() => _showTitle = true);
      } else if (_scrollController.offset <= 60 && _showTitle) {
        setState(() => _showTitle = false);
      }
    });
  }

  @override
  void dispose() {
    _scrollController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    final totalDays = int.tryParse(protocol.duration.split(' ').first) ?? 90;

    return Scaffold(
      body: Stack(
        children: [
          // Main scrollable content
          CustomScrollView(
            controller: _scrollController,
            slivers: [
              // App Bar
              SliverAppBar(
                floating: true,
                snap: true,
                elevation: 0,
                backgroundColor: isDark
                    ? const Color(0xFF102219).withOpacity(0.9)
                    : const Color(0xFFF6F8F7).withOpacity(0.9),
                leading: IconButton(
                  icon: const Icon(Icons.arrow_back),
                  onPressed: () {},
                ),
                title: AnimatedOpacity(
                  duration: const Duration(milliseconds: 300),
                  opacity: _showTitle ? 1.0 : 0.0,
                  child: const Text(
                    'PROTOCOL',
                    style: TextStyle(
                      fontSize: 16,
                      fontWeight: FontWeight.bold,
                      letterSpacing: 1.5,
                    ),
                  ),
                ),
                actions: [
                  IconButton(
                    icon: const Icon(Icons.person_outline),
                    onPressed: () {},
                  ),
                ],
              ),

              // Content
              SliverToBoxAdapter(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // Headline & Meta
                    Padding(
                      padding: const EdgeInsets.fromLTRB(20, 8, 20, 16),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            'GENERATED BY Amara AI',
                            style: TextStyle(
                              color: const Color(0xFF11D473),
                              fontSize: 12,
                              fontWeight: FontWeight.bold,
                              letterSpacing: 2,
                            ),
                          ),
                          const SizedBox(height: 4),
                          Text(
                            protocol.duration,
                            style: const TextStyle(
                              fontSize: 36,
                              fontWeight: FontWeight.w900,
                              height: 1.1,
                              letterSpacing: -0.5,
                            ),
                          ),
                          const Text(
                            'Protocol',
                            style: TextStyle(
                              fontSize: 36,
                              fontWeight: FontWeight.w900,
                              height: 1.1,
                              letterSpacing: -0.5,
                            ),
                          ),
                          const SizedBox(height: 8),
                          Text(
                            'Customized for ${protocol.personName} • Version 2.1',
                            style: TextStyle(
                              color: const Color(0xFF618975),
                              fontSize: 14,
                              fontWeight: FontWeight.w500,
                            ),
                          ),
                        ],
                      ),
                    ),

                    // Progress Snapshot Card
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 20),
                      child: _buildProgressCard(isDark, totalDays),
                    ),
                    const SizedBox(height: 24),

                    // Protocol Summary Card
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 20),
                      child: _buildProtocolSummaryCard(),
                    ),
                    const SizedBox(height: 32),

                    // Key Health Areas
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 20),
                      child: _buildHealthAreas(isDark),
                    ),
                    const SizedBox(height: 32),

                    // Protocol Phases
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 20),
                      child: _buildProtocolPhases(isDark),
                    ),
                    const SizedBox(height: 120),
                  ],
                ),
              ),
            ],
          ),
          Positioned(
            bottom: 0,
            left: 0,
            right: 0,
            child: SafeArea(
              top: false,
              child: Container(
                decoration: BoxDecoration(
                  gradient: LinearGradient(
                    begin: Alignment.topCenter,
                    end: Alignment.bottomCenter,
                    colors: [
                      Theme.of(context).colorScheme.surface.withOpacity(0.0),
                      Theme.of(context).colorScheme.surface.withOpacity(0.9),
                      Theme.of(context).colorScheme.surface,
                    ],
                  ),
                ),
                padding: const EdgeInsets.fromLTRB(20, 48, 20, 20),
                child: ElevatedButton(
                  onPressed: () {
                    Navigator.of(context).push(
                      MaterialPageRoute(
                        builder: (context) => ProtocolWeeklyRoadmapScreen(),
                      ),
                    );
                  },
                  style: ElevatedButton.styleFrom(
                    backgroundColor: const Color(0xFF11D473),
                    foregroundColor: Colors.white,
                    minimumSize: const Size(double.infinity, 56),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                    elevation: 8,
                    shadowColor: const Color(0xFF11D473).withOpacity(0.3),
                  ),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: const [
                      Text(
                        'View This Week\'s Plan',
                        style: TextStyle(
                          fontSize: 16,
                          fontWeight: FontWeight.bold,
                          letterSpacing: 0.5,
                        ),
                      ),
                      SizedBox(width: 8),
                      Icon(Icons.arrow_forward, size: 20),
                    ],
                  ),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildProgressCard(bool isDark, int totalDays) {
    final progressPercentage = protocol.progressPercentage;
    final status = progressPercentage >= 0.4 && progressPercentage <= 0.6
        ? 'On Track'
        : progressPercentage > 0.6
        ? 'Ahead'
        : 'Behind';

    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: isDark ? const Color(0xFF1A2C24) : Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(
          color: isDark
              ? Colors.white.withOpacity(0.05)
              : Colors.black.withOpacity(0.05),
        ),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.04),
            blurRadius: 20,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                'CURRENT PROGRESS',
                style: TextStyle(
                  color: const Color(0xFF618975),
                  fontSize: 11,
                  fontWeight: FontWeight.bold,
                  letterSpacing: 1.5,
                ),
              ),
              const SizedBox(height: 4),
              Row(
                crossAxisAlignment: CrossAxisAlignment.baseline,
                textBaseline: TextBaseline.alphabetic,
                children: [
                  Text(
                    'Day ${protocol.currentDay}',
                    style: const TextStyle(
                      fontSize: 28,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  Text(
                    ' / $totalDays',
                    style: TextStyle(
                      fontSize: 14,
                      fontWeight: FontWeight.w500,
                      color: const Color(0xFF618975),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 4),
              Text(
                status,
                style: const TextStyle(
                  color: Color(0xFF11D473),
                  fontSize: 14,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ],
          ),
          SizedBox(
            width: 80,
            height: 80,
            child: Stack(
              alignment: Alignment.center,
              children: [
                SizedBox(
                  width: 80,
                  height: 80,
                  child: CircularProgressIndicator(
                    value: progressPercentage,
                    strokeWidth: 6,
                    backgroundColor: isDark
                        ? Colors.white.withOpacity(0.1)
                        : Colors.grey.shade200,
                    valueColor: const AlwaysStoppedAnimation<Color>(
                      Color(0xFF11D473),
                    ),
                  ),
                ),
                const Icon(Icons.bolt, color: Color(0xFF11D473), size: 32),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildProtocolSummaryCard() {
    return Container(
      decoration: BoxDecoration(
        color: const Color(0xFF111814),
        borderRadius: BorderRadius.circular(16),
        image: DecorationImage(
          image: NetworkImage(
            'https://lh3.googleusercontent.com/aida-public/AB6AXuA-111EVT8G38jt8GB0F-N6jGP0ACvCTgJHtSg161-k_N7FuTH6sAkydEJCSjLaAjfqNoOl9uUh1u09UFisgR8t6u0wxsbMR6C-FVMTA5wvpM0UqPgNjG1VkP9P-8ops7A62_SQ5RgONj9-_xsT8TU-fj_Ik2h-QPJyPI8Ruu5Y5uQslJnDjBlXK_txf4dMgUwjdPwDRTOrkNiWosG1EWcF4lvnp9z--aEuM3CgvWUp9w_NeqBUNkXYIHQqVoRg1K-gNLLZRShljUHN',
          ),
          fit: BoxFit.cover,
          opacity: 0.4,
        ),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.2),
            blurRadius: 20,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Padding(
        padding: const EdgeInsets.all(24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                const Icon(
                  Icons.auto_awesome,
                  color: Color(0xFF11D473),
                  size: 20,
                ),
                const SizedBox(width: 8),
                const Text(
                  'PROTOCOL SUMMARY',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 13,
                    fontWeight: FontWeight.bold,
                    letterSpacing: 2,
                  ),
                ),
              ],
            ),
            const SizedBox(height: 16),
            RichText(
              text: TextSpan(
                style: const TextStyle(
                  color: Colors.white,
                  fontSize: 17,
                  fontWeight: FontWeight.w500,
                  height: 1.5,
                ),
                children: [
                  TextSpan(
                    text: 'Focus: ${protocol.name}. ',
                    style: const TextStyle(
                      color: Color(0xFF11D473),
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  TextSpan(text: protocol.summary),
                ],
              ),
            ),
            const SizedBox(height: 16),
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: protocol.summaryTags
                  .map((tag) => _buildPill(tag))
                  .toList(),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildPill(String text) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
      decoration: BoxDecoration(
        color: Colors.white.withOpacity(0.1),
        border: Border.all(color: Colors.white.withOpacity(0.1)),
        borderRadius: BorderRadius.circular(20),
      ),
      child: Text(
        text,
        style: const TextStyle(
          color: Colors.white,
          fontSize: 12,
          fontWeight: FontWeight.w600,
        ),
      ),
    );
  }

  Widget _buildHealthAreas(bool isDark) {
    return Column(
      children: [
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            const Text(
              'Key Health Areas',
              style: TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.bold,
                letterSpacing: -0.5,
              ),
            ),
            Text(
              'VIEW ALL',
              style: TextStyle(
                color: const Color(0xFF11D473),
                fontSize: 12,
                fontWeight: FontWeight.bold,
                letterSpacing: 1.5,
              ),
            ),
          ],
        ),
        const SizedBox(height: 16),
        GridView.builder(
          shrinkWrap: true,
          physics: const NeverScrollableScrollPhysics(),
          gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: 2,
            crossAxisSpacing: 16,
            mainAxisSpacing: 16,
            childAspectRatio: 1.1,
          ),
          itemCount: protocol.healthAreas.length,
          itemBuilder: (context, index) {
            final area = protocol.healthAreas[index];
            return _buildHealthAreaCard(area: area, isDark: isDark);
          },
        ),
      ],
    );
  }

  Widget _buildHealthAreaCard({
    required HealthArea area,
    required bool isDark,
  }) {
    IconData trendIcon;
    switch (area.trendType) {
      case TrendType.up:
        trendIcon = Icons.trending_up;
        break;
      case TrendType.flat:
        trendIcon = Icons.trending_flat;
        break;
      case TrendType.down:
        trendIcon = Icons.trending_down;
        break;
    }

    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: isDark ? const Color(0xFF1A2C24) : Colors.white,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.transparent),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.04),
            blurRadius: 20,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Container(
            width: 40,
            height: 40,
            decoration: BoxDecoration(
              color: area.color.withOpacity(0.1),
              borderRadius: BorderRadius.circular(20),
            ),
            child: Icon(area.icon, color: area.color, size: 24),
          ),
          Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                area.name.toUpperCase(),
                style: TextStyle(
                  color: const Color(0xFF618975),
                  fontSize: 11,
                  fontWeight: FontWeight.w600,
                  letterSpacing: 1,
                ),
              ),
              const SizedBox(height: 4),
              Text(
                area.status,
                style: const TextStyle(
                  fontSize: 20,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const SizedBox(height: 4),
              Row(
                children: [
                  Icon(trendIcon, color: area.color, size: 14),
                  const SizedBox(width: 4),
                  Text(
                    area.trend,
                    style: TextStyle(
                      color: area.color,
                      fontSize: 12,
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ],
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildProtocolPhases(bool isDark) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Text(
          'Protocol Phases',
          style: TextStyle(
            fontSize: 18,
            fontWeight: FontWeight.bold,
            letterSpacing: -0.5,
          ),
        ),
        const SizedBox(height: 16),
        Stack(
          children: [
            // Vertical line
            Positioned(
              left: 30,
              top: 24,
              bottom: 24,
              child: Container(
                width: 2,
                color: isDark
                    ? Colors.white.withOpacity(0.1)
                    : Colors.grey.shade200,
              ),
            ),
            // Phases
            Column(
              children: protocol.protocolPhases.asMap().entries.map((entry) {
                final index = entry.key;
                final phase = entry.value;
                final isCompleted = protocol.isPhaseCompleted(phase);
                final isActive = protocol.currentPhase == phase;
                final progress = isActive
                    ? protocol.getPhaseProgress(phase)
                    : null;

                return Padding(
                  padding: EdgeInsets.only(
                    bottom: index < protocol.protocolPhases.length - 1 ? 32 : 0,
                  ),
                  child: _buildPhase(
                    phase: phase,
                    isCompleted: isCompleted,
                    isActive: isActive,
                    progress: progress,
                    isDark: isDark,
                  ),
                );
              }).toList(),
            ),
          ],
        ),
      ],
    );
  }

  Widget _buildPhase({
    required ProtocolPhase phase,
    required bool isCompleted,
    required bool isActive,
    required bool isDark,
    double? progress,
  }) {
    return Opacity(
      opacity: (isCompleted && !isActive) || (!isActive && !isCompleted)
          ? 0.5
          : 1.0,
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Phase indicator
          Container(
            width: 48,
            height: 48,
            decoration: BoxDecoration(
              color: isCompleted
                  ? const Color(0xFF11D473)
                  : isActive
                  ? (isDark ? const Color(0xFF1A2C24) : Colors.white)
                  : (isDark
                        ? Colors.white.withOpacity(0.05)
                        : Colors.grey.shade100),
              shape: BoxShape.circle,
              border: isActive
                  ? Border.all(color: const Color(0xFF11D473), width: 4)
                  : Border.all(
                      color: isDark
                          ? const Color(0xFF102219)
                          : const Color(0xFFF6F8F7),
                      width: 4,
                    ),
              boxShadow: isActive || isCompleted
                  ? [
                      BoxShadow(
                        color: const Color(0xFF11D473).withOpacity(0.3),
                        blurRadius: 15,
                      ),
                    ]
                  : null,
            ),
            child: Icon(
              isCompleted
                  ? Icons.check
                  : isActive
                  ? Icons.play_arrow
                  : Icons.lock_outline,
              color: isCompleted
                  ? Colors.white
                  : isActive
                  ? const Color(0xFF11D473)
                  : Colors.grey,
              size: 24,
            ),
          ),
          const SizedBox(width: 16),
          // Phase details
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    Text(
                      phase.title,
                      style: const TextStyle(
                        fontSize: 16,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    if (isActive) ...[
                      const SizedBox(width: 8),
                      Container(
                        padding: const EdgeInsets.symmetric(
                          horizontal: 8,
                          vertical: 2,
                        ),
                        decoration: BoxDecoration(
                          color: const Color(0xFF11D473),
                          borderRadius: BorderRadius.circular(12),
                        ),
                        child: const Text(
                          'CURRENT',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 10,
                            fontWeight: FontWeight.bold,
                            letterSpacing: 0.5,
                          ),
                        ),
                      ),
                    ],
                  ],
                ),
                const SizedBox(height: 4),
                Text(
                  '${phase.range} • ${phase.summary}',
                  style: TextStyle(
                    color: isDark
                        ? Colors.grey.shade400
                        : const Color(0xFF618975),
                    fontSize: 14,
                  ),
                ),
                if (progress != null) ...[
                  const SizedBox(height: 8),
                  SizedBox(
                    width: 160,
                    child: ClipRRect(
                      borderRadius: BorderRadius.circular(8),
                      child: LinearProgressIndicator(
                        value: progress,
                        backgroundColor: isDark
                            ? Colors.white.withOpacity(0.1)
                            : Colors.grey.shade200,
                        valueColor: const AlwaysStoppedAnimation<Color>(
                          Color(0xFF11D473),
                        ),
                        minHeight: 6,
                      ),
                    ),
                  ),
                ],
              ],
            ),
          ),
        ],
      ),
    );
  }
}
